# This is a config for E2B sandbox template.
# You can use template ID (1pjz47ccqicanyrjtx05) or template name (ai-saas-website-builderx) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("ai-saas-website-builderx") # Sync sandbox
# sandbox = await AsyncSandbox.create("ai-saas-website-builderx") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('ai-saas-website-builderx')

team_id = "0d1ce645-9180-43ef-8ddc-e3a74766e34f"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "ai-saas-website-builderx"
template_id = "1pjz47ccqicanyrjtx05"
